### ISSUE TITLE
Properly install Google Analytics

### ISSUE THREAD

**Issue by theecrit** [openoakland/openoakland.org#130]
## Description

It looks like Google Analytics hasn't been tracking data accurately and it's not clear at first glance why ([GA screenshot](https://user-images.githubusercontent.com/32755410/102279967-2688df00-3ee1-11eb-9b9a-c35167c08239.png)
). GA account access can be requested from @theecrit 

#### If you are working on this issue, consider the following ongoing issues:
- [ ] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

**Comment by robdodson** [comment]
@theecrit I think this is broken because the tracking ID is incorrect.

[This line in the config](https://github.com/openoakland/openoakland.org/blob/master/_config.yml#L40) should be updated. Analytics tracking IDs always start with "UA-..".

If you go to analytics.google.com and click the gear in the bottom left hand corner it will take you to the admin page. There you can locate your property (here's an example from one of my sites):
<img width="1434" alt="Screen Shot 2021-01-07 at 12 36 37 PM" src="https://user-images.githubusercontent.com/1066253/103942483-50e74a00-50e5-11eb-9c9c-6a2b202b1a2c.png">

Clicking on the tracking code button will give you the ID
<img width="1430" alt="Screen Shot 2021-01-07 at 12 38 03 PM" src="https://user-images.githubusercontent.com/1066253/103942505-58a6ee80-50e5-11eb-8483-d9025ee8fb46.png">

For what it's worth, there's also a really handy [analytics debugging extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) you can install. If you visit the site with it enabled it logs a warning indicating the issue:
<img width="559" alt="Screen Shot 2021-01-07 at 12 40 43 PM" src="https://user-images.githubusercontent.com/1066253/103942670-9ad03000-50e5-11eb-8baa-7486f8c6eb2a.png">

**Comment by theecrit** [comment]
@robdodson Makes sense! I can just drop it into the head.html file (as opposed to the header.html file), right?

**Comment by robdodson** [comment]
I think you can just update the config.yml with the correct ID.

You would update this line: https://github.com/openoakland/openoakland.org/blob/master/_config.yml#L40
Which is used in the analytics include: https://github.com/openoakland/openoakland.org/blob/master/src/_includes/google-analytics.html#L8

If you know the ID I'm happy to do it as well :)

**Comment by theecrit** [comment]
Whelp, I tried updating to the new GA4 code and that didn't work. Then I replaced it with the standard tracker and that doesn't seem to be working either. I'm thinking the include is not working the way it's supposed to but that may be beyond me. I have to sign off for the night but may poke around this week.

**Comment by robdodson** [comment]
I think #148 may have fixed it (perhaps it was taking a while to deploy)?

But it's looking good now!

![image](https://user-images.githubusercontent.com/1066253/106553317-07183680-64ce-11eb-81ba-59676c0bcd22.png)
