### ISSUE TITLE
Make list of projects more scannable and visually compelling

### ISSUE THREAD

**Issue by rahulkgupta** [openoakland/openoakland.org#55]
At the moment, the project cell is missing certain important pieces of information. While we don't have a full list of what we should include in a project, there are certain pieces of state that we should include:

- Team (names of the people who are on the project). Let's have the names be plain text right now. We can decide to link them out later.
- Tech Stack (languages / platforms / frameworks) (ie React, Django, etc.)
- Help Needed / Needed Skills (eg https://codeforsanfrancisco.org/projects/) 
- Creation Date (When was this project created?)
- Links
   - Site
   - Github
   - Slack Channel

https://github.com/openoakland/openoakland.org/blob/master/src/_includes/project.html is the html of the project cell that needs to be updated.

https://github.com/openoakland/openoakland.org/blob/master/src/_data/active_projects.yml is the data for the projects.

https://docs.google.com/document/d/1LjwQrpd0QnQNVlyqwXkqNz4wrZPwOJvRCa7K93Eyh7s/edit#heading=h.k70ymsphcare contains the most recent data.

An example of what code for sf has in their project cell: https://raw.githubusercontent.com/sfbrigade/codeforsanfrancisco.org/master/_projects/lane-breach.md

Styles of Code for SF Projects: https://github.com/sfbrigade/codeforsanfrancisco.org/blob/master/projects/index.html

**Comment by theecrit** [comment]
I'd suggest we redesign this page so that projects appear as a self-contained "card" displaying relevant info in the following hierarchy:

- Project name
- Image (optional; we should have a fallback placeholder for projects without images; maybe an OO logo watermark)
- Brief 2-3 sentence description
- Tech stack
- Project lead
- Slack channel
- Website URL (if applicable)
- Documentation URL (Github, Google Doc, etc)
- Established date


Attached is old design that was never implemented; this could potentially be improved to be a little more dynamic: 
<img width="299" alt="Screen Shot 2019-11-12 at 8 34 39 PM" src="https://user-images.githubusercontent.com/32755410/95669688-31697100-0b38-11eb-8bc0-63295363b814.png">

**Comment by theecrit** [comment]
It looks like Hack for LA has a pretty nice way to [handle project cards](https://www.hackforla.org/#projects) using [includes](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#projects), including a really nice filter to manage the large number of projects. This would allow us to display only active projects on default, with the ability to also view inactive/etc.

It seems like a much more manageable approach, and certainly is more usable for site visitors. I could easily the project page structured like so:

- 1-sentence description of the kinds of projects we work on
- 1-2 sentences on how to find/contribute to a project (w/ a link to how to propose a new project)
- Filter menu
- List of project cards (perhaps defaulting to active projects)

**Comment by theecrit** [comment]
I've converted this page to a card-based layout, cleaned up the info hierarchy, and updated project information/links. I'm going to close this issue once the linked PR is merged and open a new one for the outstanding improvements not covered in the linked PR.

**Comment by theecrit** [comment]
Closed by #123 and carried over into #126
